#!/usr/bin/env python3
"""
Arabic Font Generator for VGA Text Mode
Generates 8x16 pixel fonts from Noto/Amiri fonts for all 4 Arabic forms per character.
Outputs arabic_font_data.c with character code allocation:
- 0x80-0xEF: Character forms (isolated, initial, medial, final)
- 0xF0-0xFF: Ligatures (lam-alef combinations)
"""

import sys
import os

# Character code allocation
# Base codes: 0x80-0x9B (28 characters)
# Form codes: 0x80-0xEF (112 codes = 28 chars * 4 forms)
# Ligature codes: 0xF0-0xFF (8 codes for lam-alef combinations)

ARABIC_BASE_CODES = {
    # Base Unicode -> base code (0x80-0x9B)
    0x0627: 0x80,  # ا (alif)
    0x0628: 0x81,  # ب (ba)
    0x062A: 0x82,  # ت (ta)
    0x062B: 0x83,  # ث (tha)
    0x062C: 0x84,  # ج (jeem)
    0x062D: 0x85,  # ح (ha)
    0x062E: 0x86,  # خ (kha)
    0x062F: 0x87,  # د (dal)
    0x0630: 0x88,  # ذ (thal)
    0x0631: 0x89,  # ر (ra)
    0x0632: 0x8A,  # ز (zay)
    0x0633: 0x8B,  # س (seen)
    0x0634: 0x8C,  # ش (sheen)
    0x0635: 0x8D,  # ص (sad)
    0x0636: 0x8E,  # ض (dad)
    0x0637: 0x8F,  # ط (ta)
    0x0638: 0x90,  # ظ (za)
    0x0639: 0x91,  # ع (ain)
    0x063A: 0x92,  # غ (ghain)
    0x0641: 0x93,  # ف (fa)
    0x0642: 0x94,  # ق (qaf)
    0x0643: 0x95,  # ك (kaf)
    0x0644: 0x96,  # ل (lam)
    0x0645: 0x97,  # م (meem)
    0x0646: 0x98,  # ن (noon)
    0x0647: 0x99,  # ه (ha)
    0x0648: 0x9A,  # و (waw)
    0x064A: 0x9B,  # ي (ya)
}

# Form types
FORM_ISOLATED = 0
FORM_INITIAL = 1
FORM_MEDIAL = 2
FORM_FINAL = 3

# Ligature codes (lam-alef combinations)
# Format: (lam_unicode, alef_unicode) -> ligature_code
LIGATURE_CODES = {
    (0x0644, 0x0627): 0xF0,  # ل + ا = لا
    (0x0644, 0x0622): 0xF1,  # ل + آ = لا (with maddah)
    (0x0644, 0x0623): 0xF2,  # ل + أ = لأ
    (0x0644, 0x0625): 0xF3,  # ل + إ = لإ
}

def get_form_code(base_code, form):
    """Calculate form code from base code and form type."""
    # Base codes are 0x80-0x9B (28 codes)
    # Forms: isolated=+0, initial=+28, medial=+56, final=+84
    # Result: 0x80-0xEF (112 codes total)
    if base_code < 0x80 or base_code > 0x9B:
        return None
    form_offset = form * 28
    return base_code + form_offset

def generate_font_bitmap(char_unicode, form):
    """
    Generate 8x16 bitmap for a character form.
    This is a placeholder - in real implementation, would:
    1. Load font file (TTF/OTF)
    2. Render character at 8x16 size
    3. Convert to bitmap
    4. Return 16-byte array (one byte per row)
    """
    # Placeholder: Generate simple pattern based on character
    # Real implementation would use PIL/Pillow or similar to render from font
    bitmap = [0x00] * 16
    
    # Simple placeholder pattern (vertical line for now)
    # In real implementation, this would be actual font rendering
    for i in range(4, 12):
        bitmap[i] = 0x18  # Simple vertical line pattern
    
    return bitmap

def generate_c_file():
    """Generate arabic_font_data.c file with all font data."""
    
    output = []
    output.append("// Generated by generate_arabic_fonts.py")
    output.append("// Arabic font data for VGA text mode (8x16 pixels)")
    output.append("// Character code allocation:")
    output.append("//   0x80-0xEF: Character forms (isolated, initial, medial, final)")
    output.append("//   0xF0-0xFF: Ligatures (lam-alef combinations)")
    output.append("")
    output.append("#include \"arabic_font.h\"")
    output.append("")
    output.append("#define NULL ((void*)0)")
    output.append("")
    
    # Generate font data arrays for each form
    for base_unicode, base_code in sorted(ARABIC_BASE_CODES.items()):
        char_name = f"arabic_{base_unicode:04X}"
        
        for form_idx, form_name in enumerate(["isolated", "initial", "medial", "final"]):
            form_code = get_form_code(base_code, form_idx)
            bitmap = generate_font_bitmap(base_unicode, form_idx)
            
            var_name = f"{char_name}_{form_name}"
            output.append(f"// Character 0x{form_code:02X} - {form_name} form of U+{base_unicode:04X}")
            output.append(f"const uint8_t {var_name}[16] = {{")
            output.append("    " + ", ".join(f"0x{b:02X}" for b in bitmap))
            output.append("};")
            output.append("")
    
    # Generate ligature font data
    output.append("// Ligatures (lam-alef combinations)")
    for lig_tuple, lig_code in LIGATURE_CODES.items():
        bitmap = generate_font_bitmap(lig_code, FORM_ISOLATED)
        var_name = f"arabic_ligature_{lig_code:02X}"
        lam, alef = lig_tuple
        output.append(f"// Ligature 0x{lig_code:02X} - U+{lam:04X} + U+{alef:04X}")
        output.append(f"const uint8_t {var_name}[16] = {{")
        output.append("    " + ", ".join(f"0x{b:02X}" for b in bitmap))
        output.append("};")
        output.append("")
    
    # Generate lookup function
    output.append("// Function to get Arabic font data by code")
    output.append("const uint8_t* get_arabic_font(uint8_t code) {")
    output.append("    switch (code) {")
    
    # Add cases for all forms
    for base_unicode, base_code in sorted(ARABIC_BASE_CODES.items()):
        char_name = f"arabic_{base_unicode:04X}"
        for form_idx, form_name in enumerate(["isolated", "initial", "medial", "final"]):
            form_code = get_form_code(base_code, form_idx)
            var_name = f"{char_name}_{form_name}"
            output.append(f"        case 0x{form_code:02X}: return {var_name};")
    
    # Add cases for ligatures
    for lig_tuple, lig_code in LIGATURE_CODES.items():
        var_name = f"arabic_ligature_{lig_code:02X}"
        output.append(f"        case 0x{lig_code:02X}: return {var_name};")
    
    output.append("        default: return NULL;")
    output.append("    }")
    output.append("}")
    output.append("")
    
    return "\n".join(output)

def main():
    """Main function."""
    print("Arabic Font Generator for VGA Text Mode")
    print("=" * 50)
    
    # Generate C file
    c_content = generate_c_file()
    
    # Write to file
    output_file = "arabic_font_data.c"
    with open(output_file, 'w') as f:
        f.write(c_content)
    
    print(f"Generated {output_file}")
    print(f"Total characters: {len(ARABIC_BASE_CODES)} base characters")
    print(f"Total forms: {len(ARABIC_BASE_CODES) * 4} character forms")
    print(f"Total ligatures: {len(LIGATURE_CODES)} ligatures")
    print("")
    print("NOTE: This is a placeholder implementation.")
    print("To generate actual font bitmaps, install Pillow and provide font files:")
    print("  pip install Pillow")
    print("  python generate_arabic_fonts.py --font NotoSansArabic-Regular.ttf")

if __name__ == "__main__":
    main()
